
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 17 16:23:11 CST 2017
//----------------------------------------------------

package Compilador.Haskell;

/** CUP generated class containing symbol constants. */
public class symH {
  /* terminals */
  public static final int PAR2 = 54;
  public static final int NUMERO = 48;
  public static final int MASMAS = 21;
  public static final int DOSPUNTOS = 27;
  public static final int PAR1 = 53;
  public static final int SQRT = 4;
  public static final int COR2 = 43;
  public static final int POT = 5;
  public static final int COR1 = 42;
  public static final int IMPR = 14;
  public static final int POR = 31;
  public static final int PUNTOYCOMA = 55;
  public static final int REVERS = 13;
  public static final int DESC = 17;
  public static final int SI = 23;
  public static final int PORCENTAJE = 20;
  public static final int ENTONCES = 24;
  public static final int PRODUCT = 12;
  public static final int NOIGUAL = 38;
  public static final int AND = 40;
  public static final int MENORIGUAL = 36;
  public static final int IGUAL = 41;
  public static final int CALCULAR = 6;
  public static final int CARACTER = 50;
  public static final int SINO = 25;
  public static final int OR = 39;
  public static final int DECC = 8;
  public static final int DIV = 32;
  public static final int MIN = 9;
  public static final int ID = 47;
  public static final int EXCLAMACION = 22;
  public static final int MAYORIGUAL = 35;
  public static final int EOF = 0;
  public static final int TRUE = 51;
  public static final int error = 1;
  public static final int COMA = 46;
  public static final int CADENA = 49;
  public static final int MENOS = 30;
  public static final int MENOR = 34;
  public static final int MOD = 3;
  public static final int LLA2 = 45;
  public static final int SUCC = 7;
  public static final int PAR = 15;
  public static final int MAYOR = 33;
  public static final int LLA1 = 44;
  public static final int SELECCIONA = 26;
  public static final int ASC = 16;
  public static final int IGUALIGUAL = 37;
  public static final int LET = 28;
  public static final int END = 19;
  public static final int SUM = 11;
  public static final int FALSE = 52;
  public static final int MAX = 10;
  public static final int DOLAR = 2;
  public static final int LENGTH = 18;
  public static final int MAS = 29;
}

