
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 01 14:44:02 CST 2017
//----------------------------------------------------

package Compilador.Graphik;

/** CUP generated class containing symbol constants. */
public class symG {
  /* terminals */
  public static final int DOSPUNTOS = 60;
  public static final int PAR2 = 53;
  public static final int MASMAS = 38;
  public static final int PAR1 = 54;
  public static final int HEREDA = 18;
  public static final int CASO = 25;
  public static final int PUBLICO = 14;
  public static final int COR2 = 52;
  public static final int MENOSMENOS = 39;
  public static final int POT = 37;
  public static final int COR1 = 51;
  public static final int INCLUIR_HK = 22;
  public static final int POR = 35;
  public static final int PUNTOYCOMA = 59;
  public static final int LLAMAR = 21;
  public static final int ENTERO = 2;
  public static final int SI = 12;
  public static final int XOR = 48;
  public static final int IMPRIMIRK = 69;
  public static final int NOIGUAL = 45;
  public static final int NOT = 49;
  public static final int AND = 47;
  public static final int MENORIGUAL = 43;
  public static final int PRIVADO = 15;
  public static final int IGUAL = 44;
  public static final int SINO = 13;
  public static final int CARACTER = 4;
  public static final int OR = 46;
  public static final int MIENTRAS = 28;
  public static final int BOOL = 6;
  public static final int DIV = 36;
  public static final int CONTINUAR = 30;
  public static final int IMPORTAR = 17;
  public static final int GRAPHIKAR_FUNCION = 32;
  public static final int ID = 62;
  public static final int MAYORIGUAL = 42;
  public static final int EOF = 0;
  public static final int LLAMARHK = 23;
  public static final int DECIMAL = 3;
  public static final int PROCESAR = 65;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int COMA = 58;
  public static final int CADENA = 5;
  public static final int MENOS = 34;
  public static final int MENOR = 41;
  public static final int MOD = 63;
  public static final int LLA2 = 56;
  public static final int MAYOR = 40;
  public static final int NUEVO = 19;
  public static final int DONDECADA = 67;
  public static final int LLA1 = 55;
  public static final int SELECCION = 24;
  public static final int PUNTO = 57;
  public static final int VACIO = 8;
  public static final int IGUALIGUAL = 50;
  public static final int PGK = 61;
  public static final int ALS = 7;
  public static final int HACER = 29;
  public static final int TERMINAR = 31;
  public static final int PROTEGIDO = 16;
  public static final int DONDE = 66;
  public static final int PARA = 27;
  public static final int DONDETODO = 68;
  public static final int RETORNAR = 20;
  public static final int FALSE = 10;
  public static final int DEFECTO = 26;
  public static final int COLUMNA = 64;
  public static final int VAR = 11;
  public static final int MAS = 33;
}

